apiVersion: v1
kind: PersistentVolume
metadata:
  name: control-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/docker/benchmarker_data