apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: control
  name: control
spec:
  containers:
  - image: dilkas/benchmarker-control
    name: control
    ports:
    - containerPort: 9998
    resources: {}
  restartPolicy: Never
status: {}
