apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: control
  name: control
spec:
  ports:
  - name: "9998"
    port: 9998
    targetPort: 9998
  selector:
    io.kompose.service: control
status:
  loadBalancer: {}
