apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: jobmanager
  name: jobmanager
spec:
  ports:
  - name: "6123"
    port: 6123
    targetPort: 6123
  - name: "6124"
    port: 6124
    targetPort: 6124
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "9250"
    port: 9250
    targetPort: 9250
  selector:
    io.kompose.service: jobmanager
status:
  loadBalancer: {}
