apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jobmanager
  name: jobmanager
spec:
  containers:
  - args:
    - jobmanager
    env:
    - name: JOB_MANAGER_RPC_ADDRESS
      value: jobmanager
    image: dominykas97/benchmarker-flink
    name: jobmanager
    ports:
    - containerPort: 6123
    - containerPort: 6124
    - containerPort: 8081
    - containerPort: 9250
    resources: {}
  restartPolicy: Never
status: {}
