apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: start
  name: start
spec:
  containers:
  - image: dominykas97/benchmarker-start
    name: start
    resources: {}
    volumeMounts:
      - name: config-files
        mountPath: /opt/flink/config
  restartPolicy: Never
  volumes:
    - name: config-files
      configMap:
        name: benchmarker-configs
status: {}
