apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift -f ../docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: taskmanager
  name: taskmanager
spec:
  ports:
  - name: "6121"
    port: 6121
    targetPort: 6121
  - name: "6122"
    port: 6122
    targetPort: 6122
  - name: "9250"
    port: 9250
    targetPort: 9250
  selector:
    io.kompose.service: taskmanager
status:
  loadBalancer: {}
