version: "3.7"
services:
  jobmanager:
    image: benchmarker
    expose:
      - "6123"
      - "9250"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    build:
      context: ../
      dockerfile: docker/Dockerfile.bench

  taskmanager:
    image: benchmarker
    expose:
      - "6121"
      - "6122"
      - "9250"
    depends_on:
      - jobmanager
      - control
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    logging:
      driver: none

  control:
    image: control
    expose:
      - "9998"
    build:
      context: ../
      dockerfile: docker/Dockerfile.control

  prometheus:
    image: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - jobmanager
      - taskmanager
    build:
      context: ../
      dockerfile: docker/Dockerfile.prom
