version: "3"
services:
  jobmanager:
    image: dominykas97/benchmarker-flink
    expose:
      - "9250"
    ports:
      - "6123:6123"
      - "6124:6124"
      - "8081:8081" # Web UI
      - "9250:9250" # for Prometheus
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    restart: "no"

  control:
    image: dominykas97/benchmarker-control
    ports:
      - "9998:9998"
    restart: "no"

  taskmanager:
    image: dominykas97/benchmarker-flink
    expose:
      - "9250"
    ports:
      - "6121:6121"
      - "6122:6122"
      - "9250:9250" # for Prometheus
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    logging:
      driver: none
    restart: "no"

  start:
    image: dominykas97/benchmarker-start
    restart: "no"

  prometheus:
    image: prom/prometheus
    #image: dominykas97/benchmarker-prom
    ports:
      - "9090:9090" # Web UI
