FROM benchmarker

ADD config/components.yaml ./
ADD config/global.yaml ./
ADD docker/control-entrypoint.sh ./
ADD target/benchmarker-0.1.jar ./

RUN chmod +x control-entrypoint.sh

ENTRYPOINT ["./control-entrypoint.sh"]
