- cpuTime: 0 # ms
  memoryUsage: 0 # MB
  outputSize: 1 # KB
  databaseOnStartup: true
  numRequests: 2
  responseSize: 2 # KB
  databaseLatency: 10 # ms
  bandwidth: 1000 # bytes/s
  intervalBetweenRequests: 10 # ms
