jobmanager.rpc.address: jobmanager
jobmanager.rpc.port: 6123
jobmanager.heap.size: 1024m

taskmanager.heap.size: 1024m
taskmanager.numberOfTaskSlots: 1

parallelism.default: 1

metrics.latency.interval: 1000
metrics.reporters: prom
metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
metrics.reporter.prom.port: 9250
