controlHostname: control
controlPort: 9998
numMessages: 5
interMessageTime: 500 # in ms
prometheusHostname: prometheus
metrics:
  - filename: throughput
    query: flink_taskmanager_job_task_operator_componentThroughput
  - filename: heap
    query: flink_taskmanager_Status_JVM_Memory_Heap_Used
  - filename: cpu
    query: flink_taskmanager_Status_JVM_CPU_Load