controlHostname: control
controlPort: 9998
prometheusHostname: prometheus
metrics:
  - name: Throughput
    filename: throughput
    query: flink_taskmanager_job_task_operator_componentThroughput
  - name: Heap Usage (MiB)
    filename: heap
    query: flink_taskmanager_Status_JVM_Memory_Heap_Used
  - name: CPU Load
    filename: cpu
    query: flink_taskmanager_Status_JVM_CPU_Load
workload:
  messagesPerSecond: 1
  experimentDuration: 1 # in seconds
  requestsPerMessage: 1
