- parents:
    - 0
  cpuTime: 170 # ms
  memoryUsage: 52 # MB
  outputSize: 52 # KB
  ioMode: regular
  numRequests: 0
  responseSize: 10240 # KB
  ioLatency: 0 # ms
  bandwidth: ??? # bytes/s
  intervalBetweenRequests: 0 # ms
- parents:
    - 1
  cpuTime: 720000 # ms
  memoryUsage: 60 # MB
  outputSize: 500 # KB
  ioMode: regular
  numRequests: 0
  responseSize: 2 # KB
  ioLatency: 0 # ms
  bandwidth: ??? # bytes/s
  intervalBetweenRequests: 0 # ms
- parents:
    - 2
  cpuTime: 90000 # ms
  memoryUsage: 664 # MB
  outputSize: 20480 # KB
  ioMode: regular
  numRequests: 0
  responseSize: 9728 # KB
  ioLatency: 0 # ms
  bandwidth: ??? # bytes/s
  intervalBetweenRequests: 0 # ms
