- parents:
    - 0
  cpuTime: 170 # ms
  memoryUsage: 52 # MB
  outputSize: 52 # KB
  io:
    mode: regular
    numRequests: 1
    responseSize: 10240
    latency: 0
    bandwidth: ???
    intervalBetweenRequests: 0
- parents:
    - 1
  cpuTime: 720000 # ms
  memoryUsage: 60 # MB
  outputSize: 500 # KB
  io:
    mode: regular
    numRequests: 2000
    responseSize: 2
    latency: 0
    bandwidth: ???
    intervalBetweenRequests: 0
- parents:
    - 2
  cpuTime: 90000 # ms
  memoryUsage: 664 # MB
  outputSize: 20480 # KB
  io:
    mode: regular
    numRequests: 21
    responseSize: 9728
    latency: 0
    bandwidth: ???
    intervalBetweenRequests: 0
